[tool.poetry]
name = "mullvad-python"
version = "0.1.0"
description = "Check Mullvad VPN connection status."
readme = "README.md"
authors = ["Franccesco Orozco <franccesco.orozco@codingdose.info>"]

[tool.poetry.dependencies]
python = "*"
requests = "^2.19"
colorama = "^0.3.9"
click = "^6.7"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[tool.poetry.scripts]
mullpy = "mullvad_python.cli:main"
